import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TableStyles from '../styles/TableStyles.module.css'
import { useState } from 'react';
import {Decimal} from 'decimal.js';
import useWindowDimensions from '../hooks/useWindowDimensions';


export default function Home() {

  const { height, width } = useWindowDimensions();

  const mileMarkers = () => {
    let arrayOfMiles = []
    for (let i = 1; i < 27; i++) {
      arrayOfMiles.push(i)
      if (i === 3) arrayOfMiles.push(raceDistances[0])
      if (i === 6) arrayOfMiles.push(raceDistances[1])
      if (i === 13) arrayOfMiles.push(raceDistances[2])
      if (i === 26) arrayOfMiles.push(raceDistances[3])
    }
    return arrayOfMiles
  }
  
  const raceDistances = [{name: '5K', mile: 3.1}, {name: '10K', mile:  6.2}, {name: 'Half Marathon', mile: 13.1}, {name: 'Marathon', mile: 26.2}]

  const [markers, setMarkers] = useState(mileMarkers())

  const splitTimes = (pacePerMile, mileMarkerArray) => {
    return mileMarkerArray.map(mileMarker => mileMarker.mile ? convertTime(mileMarker.mile * pacePerMile) : convertTime(mileMarker * pacePerMile))
  }

  const convertTime = (totalMinutes) => {
    const decimalMins = new Decimal(totalMinutes);
    const sixty = new Decimal(60);
    const hours = Decimal.floor(decimalMins.div(sixty)).d[0];
    const minutes = Decimal.round(decimalMins.mod(sixty)).d[0].toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false});
    const x = decimalMins.mod(sixty) - Decimal.floor(decimalMins.mod(sixty));
    const seconds = Decimal.round(Decimal.mul(x, sixty)).d[0].toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false});
    return { hours, minutes, seconds }
  }

  const [splits, setSplits] = useState(splitTimes(8, markers))

  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={TableStyles.container}>
      paceCalc
      <table className={TableStyles.tableContainer} >
        <thead>
          <tr className={`${TableStyles.row} ${TableStyles.topRow}`}>
            <th className={TableStyles.rowCell}>
              <span>discance &rarr;</span><br/>
              <span>pace &darr;</span>
            </th>
            {markers.map((marker) => 
              marker.name ? <th className={TableStyles.rowCell} key={marker.mile}><span>{marker.name}</span>
              <br/>
              <span>{marker.mile}</span>
              </th> : <th className={TableStyles.rowCell} key={ marker }>
                <span>Mile</span>
                <br/>
                <span>{ marker }</span>
              </th> )}
          </tr>
        </thead>
        <tbody>
          <tr className={`${TableStyles.row} ${TableStyles.time}`}>
              <th className={`${TableStyles.rowCell} ${TableStyles.topRow}`}>{ `${splits[0].minutes}:00` }</th>
            { splits.map(split => <th className={TableStyles.rowCell} key={split.hours + split.minutes + split.seconds}>{ split.hours > 0 ? `${split.hours}:`: '' }{ split.minutes }:{ split.seconds }</th>) }     
          </tr>
        </tbody>
      </table>
      </main>

      <footer className={styles.footer}>
        {width <= 768 ? 'mobile' : 'desktop'}
        <div>
          <span>height: {height}</span><br/>
          <span>width: {width}</span>
        </div>
      </footer>
    </div>
  )
}
